tests(proxy-wasm) skip local Go tests if examples did not compile
Sometimes the Go version installed on the host is not supported by
proxy-wasm-go-sdk:

    compiling Go examples...
    make[1]: Entering directory '/home/chasum/code/ngx_wasm_module/work/downloads/proxy-wasm-go-sdk'
    error: requires go version 1.18 through 1.19, got go1.20

With this patch, unless we are running our integration tests
(`CI=true`), we now skip these tests with warnings instead of completely
preventing the test suite to run.